{
 "title": "DASH",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Inovações por Setor",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "banco",
     "rawSql": "SELECT COUNT(setor) FROM banco.tbl_inovacao WHERE setor = 'TI' GROUP BY setor LIMIT 50 "
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Plan. De Série'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Fábrica Piloto'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Manutenção Site'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Estamparia'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Armação'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Pintura'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Montagem Final'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'VW Componentes'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'QA Processos'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Eng. Industrial'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Logística'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 0 },
   "targets": [
    {
     "dataset": "banco",
     "rawSql": "SELECT COUNT(setor), setor FROM banco.tbl_inovacao GROUP BY setor ORDER BY setor DESC "
    }
   ]
  },
  {
   "title": "Em Escalação",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "banco",
     "rawSql": "SELECT COUNT(status) FROM banco.tbl_inovacao WHERE status = 'Escalação' GROUP BY status ORDER BY COUNT(status) DESC "
    }
   ]
  },
  {
   "title": "No Prazo",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "banco",
     "rawSql": "SELECT COUNT(status) FROM banco.tbl_inovacao WHERE status = 'No prazo' GROUP BY status ORDER BY COUNT(status) DESC "
    }
   ]
  },
  {
   "title": "Handlungsfeld",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "banco",
     "rawSql": "SELECT COUNT(handlungsfeld) FROM banco.tbl_inovacao WHERE handlungsfeld = 'SGK' GROUP BY handlungsfeld LIMIT 50 "
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(handlungsfeld)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  handlungsfeld = 'Ramp-up Excellence'\r\nGROUP BY\r\n  handlungsfeld\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(handlungsfeld)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  handlungsfeld = 'Low-Expenditure Factories of the Future'\r\nGROUP BY\r\n  handlungsfeld\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(handlungsfeld)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  handlungsfeld = 'Stable Customer Order Process'\r\nGROUP BY\r\n  handlungsfeld\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(handlungsfeld)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  handlungsfeld = 'Team of the Future'\r\nGROUP BY\r\n  handlungsfeld\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(handlungsfeld)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  handlungsfeld = 'Sustainable Structures'\r\nGROUP BY\r\n  handlungsfeld\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(handlungsfeld)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  handlungsfeld = 'Produtivity'\r\nGROUP BY\r\n  handlungsfeld\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(handlungsfeld)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  handlungsfeld = 'Rework-free Products and Processes'\r\nGROUP BY\r\n  handlungsfeld\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(handlungsfeld)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  handlungsfeld = 'Zero Impact Factory'\r\nGROUP BY\r\n  handlungsfeld\r\nLIMIT\r\n  50"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 9, "y": 7 },
   "targets": [
    {
     "dataset": "banco",
     "rawSql": "SELECT COUNT(handlungsfeld), handlungsfeld FROM banco.tbl_inovacao GROUP BY handlungsfeld ORDER BY COUNT(handlungsfeld) DESC LIMIT 50 "
    }
   ]
  },
  {
   "title": "Em atraso",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "banco",
     "rawSql": "SELECT COUNT(status) FROM banco.tbl_inovacao WHERE status = 'Em atraso' GROUP BY status ORDER BY COUNT(status) DESC "
    }
   ]
  },
  {
   "title": "Inovações por pessoa",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "banco",
     "rawSql": "SELECT COUNT(setor), MAX(responsible) FROM banco.tbl_inovacao WHERE responsible <> '' GROUP BY responsible ORDER BY COUNT(setor) DESC "
    }
   ]
  }
 ]
}