{
 "title": "DASH",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Inovações por pessoa",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "banco",
     "rawSql": "SELECT COUNT(setor), MAX(responsible) FROM banco.tbl_inovacao WHERE responsible <> '' GROUP BY responsible LIMIT 50 "
    }
   ]
  },
  {
   "title": "INOVAÇÕES POR SETOR",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 0 },
   "targets": [
    {
     "dataset": "banco",
     "rawSql": "SELECT COUNT(id), setor FROM banco.tbl_inovacao GROUP BY setor LIMIT 50 "
    }
   ]
  },
  {
   "title": "Inovações por Área",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "areaM2" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "banco",
     "rawSql": "SELECT COUNT(setor) FROM banco.tbl_inovacao WHERE setor = 'TI' GROUP BY setor LIMIT 50 "
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Plan. De Série'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Fábrica Piloto'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Manutenção Site'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Estamparia'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Armação'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Pintura'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "dataset": "banco",
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Montagem Final'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'VW Componentes'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'QA Processos'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Eng. Industrial'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    },
    {
     "rawSql": "SELECT\r\n  COUNT(setor)\r\nFROM\r\n  banco.tbl_inovacao\r\nWHERE\r\n  setor = 'Logística'\r\nGROUP BY\r\n  setor\r\nLIMIT\r\n  50"
    }
   ]
  }
 ]
}