INSERT INTO tbl_setor (Id, nome_Setor) VALUES (1, 'Plan. De Série')
INSERT INTO tbl_setor (Id, nome_Setor) VALUES (2, 'Fábrica Piloto')
INSERT INTO tbl_setor (Id, nome_Setor) VALUES (3, 'Manutenção Site')
INSERT INTO tbl_setor (Id, nome_Setor) VALUES (4, 'Estamparia')
INSERT INTO tbl_setor (Id, nome_Setor) VALUES (5, 'Armação')
INSERT INTO tbl_setor (Id, nome_Setor) VALUES (6, 'Pintura')
INSERT INTO tbl_setor (Id, nome_Setor) VALUES (7, 'Montagem Final')
INSERT INTO tbl_setor (Id, nome_Setor) VALUES (8, 'VW Componentes')
INSERT INTO tbl_setor (Id, nome_Setor) VALUES (9, 'QA Processos')
INSERT INTO tbl_setor (Id, nome_Setor) VALUES (10, 'Eng. Industrial')
INSERT INTO tbl_setor (Id, nome_Setor) VALUES (11, 'Logística')
INSERT INTO tbl_setor (Id, nome_Setor) VALUES (12, 'TI')
